### ISSUE TITLE
[Development] Email Module for MDC

### ISSUE THREAD

**Issue by wenqingyu** [airplake/message-distributing-center#9]
**Task Description**
MDC need Email Sending module to handle business email.

**Acceptance Criteria**

- [ ] This module should majorly **independent** from other modules such as SMS module.
- [ ] All the **email adaptors** for different vendors such as Gmail, SMTPCorp, 163, Ali SMTP should be pluggable as **NPM packages**. 
- [ ] **Adaptors' priority** should be **configurable** in project configure file.

- [ ] Email module should provide **email template engine** to manage email content.

**Task need to break down**

**Comment by wenqingyu** [comment]
@shadow88sky 这个任务需要细化成详细的issues，建好之后分发到群里让大家领取，谢谢！
